"use client"

import Image from "next/image"
import { ArrowUpRight } from "lucide-react"
import { Footer } from "@/components/footer"
import { SiteHeader } from "@/components/site-header"

const farmImage = "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1200&q=85"
const letterImage = "/images/about-letter-orchard.jpg"

const missions = ["Tuyên truyền, hướng dẫn kỹ thuật canh tác mới cho người dân.", "Là đơn vị liên kết đáng tin cậy, hỗ trợ người nông dân từ kỹ thuật, quy trình đến đầu ra.", "Xây dựng chuỗi liên kết từ đầu vào, sản xuất đến hệ thống đầu ra với siêu thị và doanh nghiệp thương mại.", "Góp phần xây dựng nền nông nghiệp giá trị cao và bền vững.", "Cải thiện môi trường đất, nước và không khí thông qua các giải pháp canh tác an toàn.", "Góp phần xây dựng thương hiệu nông sản địa phương và quốc gia."]
type Milestone = { year: string; title: string; text?: string; items?: string[]; image?: string }

const milestones: Milestone[] = [
  { year: "2021", title: "Tháng 3/2021: Khởi đầu từ quyết tâm đổi mới", text: "HTX Nông nghiệp Sạch Hưng Thịnh Phát chính thức được thành lập theo Giấy chứng nhận ĐKKD số 1201647060. Dù là đơn vị non trẻ với vốn điều lệ ban đầu hơn 2 tỷ đồng, HTP đã đặt nền móng vững chắc bằng định hướng làm nông nghiệp sạch và chuẩn hóa quy trình ngay từ ngày đầu.", image: "/images/milestone-2021.jpg" },
  { year: "2022", title: "Chuẩn hóa nhà xưởng & Hệ thống an toàn thực phẩm", items: ["Đạt Giấy chứng nhận Cơ sở Đủ điều kiện An toàn thực phẩm số 052/2022/NNPTNT-TG do Sở NN&PTNT Tiền Giang cấp ngày 19/04/2022.", "Đạt chứng nhận Hệ thống quản lý an toàn thực phẩm HACCP Codex 2020 cho hoạt động sơ chế, đóng gói thanh long và nông sản."] },
  { year: "2023", title: "Bứt phá xuất khẩu chính ngạch", items: ["Triển khai thiết lập hệ thống mã số vùng trồng nông nghiệp bền vững và hoàn thiện nhà máy sơ chế đóng gói.", "Xuất khẩu chính ngạch thành công thanh long sang các thị trường quốc tế khắt khe như Mỹ, Trung Đông... đạt doanh thu 203 tỷ đồng/năm."], image: "/images/milestone-2023.jpg" },
  { year: "2024", title: "Mở rộng vùng nguyên liệu chuẩn GLOBALG.A.P.", items: ["Phát triển chuỗi liên kết vùng nguyên liệu đạt chuẩn GLOBALG.A.P. gần 115 ha và mở rộng các vùng trồng VietGAP.", "Đa dạng hóa danh mục sản phẩm xuất khẩu: Thanh long (ruột đỏ, ruột trắng, vỏ vàng), dừa tươi, dưa hấu, xoài…"] },
  { year: "2025", title: "Đẩy mạnh liên kết & Chế biến sâu", text: "Mở rộng liên kết xuất khẩu và nhận gia công, sơ chế đóng gói cho các đối tác trong và ngoài nước.", image: "/images/milestone-2025.jpg" },
  { year: "2026", title: "Hướng đến chuỗi giá trị toàn diện", items: ["Mở rộng lĩnh vực thương mại dịch vụ nội địa và xuất khẩu.", "Đầu tư phát triển vùng nguyên liệu và xây dựng chuỗi liên kết bền vững.", "Đầu tư máy móc, thiết bị đông lạnh nông sản phục vụ chế biến sâu.", "Đào tạo nhân sự, nâng cao năng lực quản lý và vận hành.", "Truyền thông thay đổi hành vi canh tác của bà con nông dân theo hướng an toàn, hiệu quả."] },
]

export function AboutPage() {
  return <div className="min-h-screen bg-[#f0e8dd] text-[#2d3026]">
    <SiteHeader />
    <main>
      <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-40 lg:grid-cols-[1fr_.85fr] lg:items-center lg:px-8 lg:pb-32 lg:pt-48"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ba466d]">Về chúng tôi</p><h1 className="mt-6 max-w-3xl font-serif text-5xl leading-[.96] tracking-[-.04em] text-[#822944] sm:text-7xl">Kiến tạo giá trị bền vững<br /><em className="font-normal text-[#6e8644]">từ vùng đất Tiền Giang</em></h1><p className="mt-7 max-w-xl text-base leading-7 text-[#626751]">Từ những vùng thanh long trù phú của Chợ Gạo, Hưng Thịnh Phát xây dựng một chuỗi nông nghiệp sạch, minh bạch và hướng đến thị trường toàn cầu.</p></div><ImageSlot src={farmImage} alt="Vùng trồng nông nghiệp Tiền Giang" className="aspect-[4/5] rotate-2" /></section>
      <section id="cau-chuyen" className="bg-[#fffaf3] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">Câu chuyện Hưng Thịnh Phát</p><h2 className="mt-5 font-serif text-5xl text-[#822944]">Thư Ngỏ</h2><blockquote className="mt-8 border-l-4 border-[#ba466d] pl-5 font-serif text-2xl leading-snug text-[#6e8644]">“Kính chào Quý đối tác, Doanh nghiệp & Khách hàng!”</blockquote><div className="mt-7 space-y-5 text-sm leading-7 text-[#626751]"><p>Tiền Giang từ lâu đã được biết đến là vùng đất phù sa màu mỡ, thủ phủ của những trái thanh long ruột đỏ, ruột trắng mọng ngọt và các dòng nông sản nhiệt đới trù phú. Chúng tôi sinh ra và lớn lên trên mảnh đất này, chứng kiến sự dãi dầu nắng mưa của bà con nông dân và hiểu rõ tiềm năng to lớn của nông sản Việt trên bản đồ thế giới.</p><p>Tuy nhiên, rào cản về quy chuẩn canh tác, công nghệ bảo quản sau thu hoạch và tính minh bạch thương hiệu từng khiến nông sản địa phương gặp nhiều bấp bênh. Bằng niềm tin về một nền nông nghiệp sạch, tử tế và tự chủ, Hợp tác xã Nông nghiệp Sạch Hưng Thịnh Phát đã ra đời.</p><p>Chúng tôi chọn đồng hành trực tiếp cùng người nông dân từ khâu cải tạo đất, hướng dẫn kỹ thuật VietGAP/GLOBALG.A.P., đến đầu tư nhà máy sơ chế, đóng gói khép kín đạt chuẩn HACCP.</p></div></div><ImageSlot src={letterImage} alt="Vùng trồng thanh long Hưng Thịnh Phát" className="aspect-[4/5]" /></div></section>
      <section id="tam-nhin" className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">Định hướng phát triển</p><h2 className="mt-5 font-serif text-5xl text-[#822944]">Tầm Nhìn & Sứ Mệnh</h2><div className="mt-12 grid gap-5 lg:grid-cols-2"><article className="rounded-[30px] bg-[#6e8644] p-8 text-[#fffaf3] lg:p-12"><p className="text-sm font-bold tracking-[.2em] text-[#e8cda8]">01</p><h3 className="mt-12 font-serif text-4xl">TẦM NHÌN</h3><p className="mt-6 max-w-xl text-sm leading-7 text-white/75">Hợp tác xã Nông nghiệp Sạch Hưng Thịnh Phát mong muốn trở thành một trong những doanh nghiệp tiêu biểu về vùng nguyên liệu, sản xuất, chuyển giao công nghệ, sơ chế, bảo quản, chế biến sâu sau thu hoạch, nông nghiệp tuần hoàn và phân phối nông sản tại Tiền Giang và trên cả nước.</p></article><article className="rounded-[30px] bg-[#822944] p-8 text-[#fffaf3] lg:p-12"><p className="text-sm font-bold tracking-[.2em] text-[#e8cda8]">02</p><h3 className="mt-12 font-serif text-4xl">SỨ MỆNH</h3><p className="mt-5 text-sm text-white/75">Đồng hành cùng Nông dân, Người tiêu dùng, Người lao động, Xã hội, Nông nghiệp, Môi trường và Quốc gia.</p><ol className="mt-7 grid gap-3">{missions.map((item, index) => <li key={item} className="flex gap-3 border-t border-white/15 pt-3 text-sm leading-6 text-white/80"><span className="font-serif text-[#e8cda8]">0{index + 1}</span><span>{item}</span></li>)}</ol></article></div></div></section>
      <section className="overflow-hidden bg-[#fffaf3] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">Giá trị thương hiệu</p><h2 className="mt-5 max-w-2xl font-serif text-5xl text-[#822944]">Trọn Vẹn Trong Từng Giá Trị</h2><p className="mt-5 max-w-xl text-[#626751]">Ba giá trị tạo nên cách Hưng Thịnh Phát chăm chút cho sản phẩm, người tiêu dùng và cộng đồng nông nghiệp địa phương.</p><div className="mt-8 flex items-end justify-between md:hidden"><Image src="/images/value-mascot-red.png" alt="Mascot thanh long đỏ Long Gia" width={150} height={175} className="-ml-5 w-32 -rotate-6 mix-blend-multiply" /><Image src="/images/value-mascot-white.png" alt="Mascot thanh long trắng Long Gia" width={150} height={175} className="-mr-5 w-32 rotate-6 mix-blend-multiply" /></div><div className="relative mt-4 md:mt-12 lg:px-12"><Image src="/images/value-mascot-red.png" alt="Mascot thanh long đỏ Long Gia" width={210} height={245} className="pointer-events-none absolute -bottom-12 -left-14 z-20 hidden w-36 -rotate-6 mix-blend-multiply md:block lg:-bottom-16 lg:-left-24 lg:w-52" /><Image src="/images/value-mascot-white.png" alt="Mascot thanh long trắng Long Gia" width={210} height={245} className="pointer-events-none absolute -bottom-12 -right-14 z-20 hidden w-36 rotate-6 mix-blend-multiply md:block lg:-bottom-16 lg:-right-24 lg:w-52" /><div className="relative z-10 grid gap-4 md:grid-cols-3"><ValueCard tone="pink" title="TRỌN AN TÂM" items={["Minh bạch nguồn gốc", "Quy trình canh tác", "Tiêu chuẩn an toàn", "Sự tin tưởng người tiêu dùng"]} /><ValueCard tone="green" title="TRỌN DINH DƯỠNG" items={["Giữ trọn dưỡng chất", "Sản phẩm tươi ngon", "Giá trị tự nhiên", "Sức khỏe người tiêu dùng"]} /><ValueCard tone="gold" title="TRỌN TRÁI TIM" items={["Tâm huyết người nông dân", "Vùng đất Tiền Giang", "Sinh kế bền vững", "Niềm tự hào nông sản Việt"]} /></div></div></div></section>
      <section id="hanh-trinh" className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">Hành trình phát triển</p><h2 className="mt-5 max-w-3xl font-serif text-5xl leading-tight text-[#822944]">Từ khởi đầu địa phương<br /><em className="font-normal text-[#6e8644]">đến chuỗi giá trị bền vững</em></h2><p className="mt-5 max-w-xl text-[#626751]">Từng cột mốc là một bước tiến trong hành trình chuẩn hóa vùng trồng, nâng cấp năng lực sản xuất và mở rộng thị trường.</p><div className="relative mt-16 before:absolute before:bottom-0 before:left-[18px] before:top-0 before:w-px before:bg-[#d5c8ba] md:before:left-1/2">{milestones.map((item, index) => <article key={item.year} className="relative grid gap-6 pb-14 pl-12 last:pb-0 md:grid-cols-2 md:gap-14 md:pl-0"><span className="absolute left-0 top-0 flex size-9 items-center justify-center rounded-full bg-[#ba466d] font-serif text-sm text-white md:left-1/2 md:-translate-x-1/2">{item.year.slice(2)}</span><div className={`${index % 2 ? "md:col-start-2" : "md:col-start-1 md:text-right"}`}><p className="font-serif text-3xl text-[#ba466d]">{item.year}</p><h3 className="mt-2 font-serif text-2xl text-[#822944]">{item.title}</h3>{item.text && <p className="mt-3 text-sm leading-7 text-[#626751]">{item.text}</p>}{item.items && <ul className="mt-3 space-y-2 text-sm leading-7 text-[#626751]">{item.items.map(detail => <li key={detail} className="flex gap-2 before:mt-[11px] before:size-1.5 before:shrink-0 before:rounded-full before:bg-[#ba466d]">{detail}</li>)}</ul>}</div>{item.image && <ImageSlot src={item.image} alt={item.title} className="aspect-[16/8] md:col-span-1" />}</article>)}</div></div></section>
      <section id="lien-he" className="mx-5 mb-20 overflow-hidden rounded-[32px] bg-[#6e8644] px-6 py-20 text-center text-[#fffaf3] lg:mx-auto lg:max-w-7xl lg:px-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#e8cda8]">Hợp tác cùng Hưng Thịnh Phát</p><h2 className="mx-auto mt-5 max-w-3xl font-serif text-5xl leading-tight sm:text-6xl">Cùng chúng tôi đưa<br /><em className="font-normal text-[#e8cda8]">nông sản Việt đi xa hơn</em></h2><p className="mx-auto mt-6 max-w-xl leading-7 text-white/75">Hưng Thịnh Phát sẵn sàng đồng hành cùng doanh nghiệp xuất nhập khẩu, hệ thống siêu thị, đại lý phân phối và khách hàng mua sỉ.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="mailto:trungquy077@gmail.com" className="rounded-full bg-[#fffaf3] px-7 py-3.5 text-sm font-bold text-[#822944] transition duration-300 hover:-translate-y-0.5 hover:bg-[#e8cda8] hover:shadow-lg focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">Liên hệ hợp tác <ArrowUpRight className="ml-1 inline" size={16} /></a><a href="tel:0919831055" className="rounded-full border border-white/40 px-7 py-3.5 text-sm font-bold transition duration-300 hover:-translate-y-0.5 hover:border-white hover:bg-white/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">0919 831 055</a></div></section>
    </main><Footer />
  </div>
}

function ImageSlot({ src, alt, className = "" }: { src: string; alt: string; className?: string }) { return <div className={`relative overflow-hidden rounded-[30px] bg-[#d9d2c6] ${className}`}><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition duration-700 hover:scale-105" />{/* TODO: Replace with real Long Gia image */}</div> }
function ValueCard({ title, items, tone }: { title: string; items: string[]; tone: "pink" | "green" | "gold" }) { const colors = { pink: "bg-[#f2d8df] text-[#822944]", green: "bg-[#dfe5cd] text-[#40512b]", gold: "bg-[#f1e2bf] text-[#785b2f]" }; return <article className={`min-h-[300px] rounded-[28px] p-7 ${colors[tone]} transition duration-500 hover:-translate-y-2 hover:shadow-xl`}><h3 className="font-serif text-2xl">{title}</h3><ul className="mt-5 grid gap-3 text-sm leading-6">{items.map(item => <li key={item} className="border-t border-current/15 pt-3">{item}</li>)}</ul></article> }
