"use client"

import Image from "next/image"
import { useState } from "react"
import { ArrowRight, Check, ChevronRight, MapPin, Sprout } from "lucide-react"
import { Footer } from "@/components/footer"
import { SiteHeader } from "@/components/site-header"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"

const stages = [
  { no: "01", title: "Chong Đèn Kích Hoa", time: "Khoảng 20 – 30 ngày", short: "Kích thích cây ra hoa đồng loạt theo chu kỳ.", detail: "Hệ thống đèn LED chuyên dụng được thắp sáng từ 22:00 đến 02:00 hằng ngày nhằm kích thích trụ thanh long ra hoa đồng loạt theo chu kỳ. Kỹ thuật viên HTX liên tục kiểm tra mật độ ánh sáng và độ ẩm đất để đảm bảo tỷ lệ đậu hoa tối ưu nhất.", image: "/images/stage-01-lighting.jpg" },
  { no: "02", title: "Tỉa Nhánh", time: "Khoảng 10 – 15 ngày", short: "Chăm sóc và tập trung dưỡng chất cho những nhánh khỏe mạnh.", detail: "Cắt tỉa những cành già, cành yếu hoặc sâu bệnh để tập trung dinh dưỡng nuôi các nhánh khỏe mạnh. Toàn bộ quá trình sử dụng phân bón hữu cơ sinh học theo đúng tiêu chuẩn VietGAP/GLOBALG.A.P.", image: "/images/stage-02-pruning.jpg" },
  { no: "03", title: "Bọc Trái", time: "Khoảng 30 – 35 ngày", short: "Bảo vệ trái non trong giai đoạn phát triển quan trọng.", detail: "Khi quả non hình thành, từng trái thanh long được công nhân dùng túi chuyên dụng bọc cẩn thận. Công đoạn này giúp bảo vệ trái khỏi côn trùng, sâu bọ tự nhiên mà hoàn toàn không cần dùng đến thuốc bảo vệ thực vật hóa học.", image: "/images/stage-02-pruning.jpg" },
  { no: "04", title: "Thu Hoạch", time: "Khi trái đạt độ chín 85 – 90%", short: "Thu hoạch đúng độ chín, sơ chế và chuẩn bị giao đến khách hàng.", detail: "Trái thanh long đạt độ chín chuẩn, tai xanh cứng, ruột mọng ngọt được hái thủ công vào buổi sáng sớm. Sau đó tiến hành phân loại, làm sạch và đóng gói theo quy trình an toàn thực phẩm trước khi giao đến tận tay khách hàng.", image: "/images/stage-03-04.jpg" },
]

const pillars = Array.from({ length: 8 }, (_, i) => ({ id: `LG-${String(27 + i).padStart(3, "0")}`, owner: i % 3 === 0 ? "Nguyễn Văn An" : i % 3 === 1 ? "Trụ đang sinh trưởng" : "Sẵn sàng nhận nuôi", status: i % 3 === 2 ? "available" : "growing", stage: stages[i % stages.length].title }))

export function LongGiaNhaToiPage() {
  const [stage, setStage] = useState(0)
  const [adoptOpen, setAdoptOpen] = useState(false)
  const [success, setSuccess] = useState(false)
  const active = stages[stage]

  return <div className="min-h-screen bg-[#f0e8dd] text-[#2d3026]">
    <SiteHeader />
    <main>
      <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-40 lg:grid-cols-[1fr_.85fr] lg:items-center lg:px-8 lg:pt-48"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ba466d]">Nông nghiệp số · Tiền Giang</p><h1 className="mt-5 max-w-3xl font-serif text-6xl leading-[.92] tracking-[-.06em] text-[#822944] sm:text-8xl">Long Gia<br /><em className="font-normal text-[#6e8644]">Nhà Tôi</em></h1><h2 className="mt-8 max-w-xl font-serif text-2xl leading-tight text-[#2d3026]">Nhận Nuôi Một Trụ Thanh Long, Theo Dõi Cả Một Hành Trình</h2><p className="mt-5 max-w-xl leading-7 text-[#626751]">Long Gia Nhà Tôi là mô hình nhận nuôi trụ thanh long điện tử do Hợp tác xã Nông nghiệp Sạch Hưng Thịnh Phát phát triển. Theo dõi hành trình sinh trưởng của cây ngay trên website.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => setAdoptOpen(true)} className="rounded-full bg-[#ba466d] px-6 py-3.5 font-semibold text-white">Đăng Ký Nhận Nuôi <ArrowRight className="ml-2 inline" size={16} /></button><a className="rounded-full border border-[#ba466d]/35 px-6 py-3.5 font-semibold text-[#822944]" href="#hanh-trinh">Xem Hành Trình Canh Tác</a></div><div className="mt-12 grid max-w-lg grid-cols-3 gap-4 border-t border-[#d5c8b9] pt-6"><div><p className="font-serif text-3xl text-[#ba466d]">150ha</p><p className="mt-1 text-xs text-[#626751]">Vùng trồng liên kết</p></div><div><p className="font-serif text-3xl text-[#ba466d]">100%</p><p className="mt-1 text-xs text-[#626751]">Theo dõi minh bạch</p></div><div><p className="font-serif text-3xl text-[#ba466d]">48h</p><p className="mt-1 text-xs text-[#626751]">Thu hoạch đến giao</p></div></div></div><div className="relative mx-auto w-full max-w-md"><div className="relative aspect-[.78] overflow-hidden rounded-[38px] bg-[#6e8644] shadow-2xl"><Image src="/images/long-gia-pillar.jpg" alt="Trụ thanh long tại vùng trồng" fill className="object-cover" priority /><div className="absolute inset-0 bg-gradient-to-t from-[#2d3026]/65 to-transparent" /><p className="absolute bottom-7 left-7 text-sm text-white/75">Long Gia Nhà Tôi</p></div><div className="absolute -bottom-7 -left-5 rounded-2xl border border-white/80 bg-[#fffaf3]/95 p-5 shadow-xl backdrop-blur"><p className="font-serif text-lg text-[#822944]">Thanh Long Ruột Đỏ HTP</p><p className="mt-2 text-xs text-[#626751]">Mã trụ: <b>LG-HTP-027</b></p><p className="mt-1 text-xs text-[#626751]">Trạng thái: <b className="text-[#6e8644]">Đang phát triển</b></p><p className="mt-1 text-xs text-[#626751]">Cập nhật: 20/07/2026</p></div></div></section>
      <section id="hanh-trinh" className="bg-[#fffaf3] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">Nhật ký canh tác</p><h2 className="mt-4 max-w-2xl font-serif text-5xl leading-tight text-[#822944]">Theo Dõi Từng Giai Đoạn<br /><em className="font-normal text-[#6e8644]">Sinh Trưởng Thanh Long</em></h2><p className="mt-5 max-w-xl leading-7 text-[#626751]">Mọi công đoạn chăm sóc đều được cập nhật minh bạch, giúp bạn dễ dàng theo dõi hành trình lớn lên của trụ thanh long nhà mình.</p><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{stages.map((item, i) => <button key={item.no} onClick={() => setStage(i)} className={`overflow-hidden rounded-3xl border text-left transition hover:-translate-y-1 ${stage === i ? "border-[#ba466d] bg-[#f7e7ea] shadow-lg" : "border-[#ded3c6] bg-white"}`}><div className="relative h-44"><Image src={item.image} alt="" fill className="object-cover" />{/* TODO: Replace with real cultivation stage photo */}</div><div className="p-5"><p className="text-xs font-bold text-[#ba466d]">GIAI ĐOẠN {item.no}</p><h3 className="mt-3 font-serif text-xl text-[#822944]">{item.title}</h3><p className="mt-2 text-xs text-[#6e8644]">{item.time}</p><p className="mt-3 text-sm leading-6 text-[#626751]">{item.short}</p></div></button>)}</div><div className="mt-6 grid overflow-hidden rounded-3xl bg-[#f0e8dd] lg:grid-cols-[.8fr_1.2fr]"><div className="relative min-h-[280px]"><Image src={active.image} alt="" fill className="object-cover" />{/* TODO: Replace with real cultivation stage photo */}</div><div className="p-8 lg:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">Giai đoạn hiện tại · {active.no}</p><h3 className="mt-4 font-serif text-4xl text-[#822944]">{active.title}</h3><p className="mt-3 font-semibold text-[#6e8644]">{active.time}</p><p className="mt-5 max-w-xl leading-7 text-[#626751]">{active.detail}</p><span className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#ba466d] px-4 py-2 text-xs font-semibold text-white"><Check size={14} /> Đang được cập nhật</span></div></div></div></section>
      <section className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">Vườn Long Gia</p><h2 className="mt-4 max-w-2xl font-serif text-5xl leading-tight text-[#822944]">Bản Đồ Trụ Thanh Long<br /><em className="font-normal text-[#6e8644]">Của Bạn Tại Long Gia</em></h2><p className="mt-5 max-w-xl leading-7 text-[#626751]">Khám phá các trụ thanh long đang phát triển, đã được nhận nuôi hoặc sẵn sàng để bạn bắt đầu hành trình.</p><div className="mt-10 flex flex-wrap gap-2"><span className="rounded-full bg-[#ba466d] px-4 py-2 text-xs font-semibold text-white">Tất cả</span><span className="rounded-full border border-[#d7cabb] px-4 py-2 text-xs">Đang được nhận nuôi</span><span className="rounded-full border border-[#d7cabb] px-4 py-2 text-xs">Sẵn sàng nhận nuôi</span></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{pillars.map((pillar, i) => <article key={pillar.id} className="rounded-3xl border border-[#ded3c6] bg-[#fffaf3] p-5 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-[#f7e7ea] px-3 py-1 text-xs font-bold text-[#ba466d]">{pillar.id}</span><span className={`text-xs font-semibold ${pillar.status === "available" ? "text-[#ba466d]" : "text-[#6e8644]"}`}>{pillar.status === "available" ? "Còn trống" : "Đang phát triển"}</span></div><div className="relative my-7 flex h-20 items-center justify-center overflow-hidden rounded-2xl bg-[#e4e8ce] text-[#6e8644]">{pillar.status === "available" ? <Sprout size={38} /> : <Image src={i % 2 === 0 ? "/images/garden-fruit-closeup.jpg" : "/images/garden-fruit-cluster.jpg"} alt="" fill className="object-cover" />}</div><p className="font-serif text-lg text-[#822944]">Thanh Long Ruột Đỏ HTP</p><p className="mt-2 text-xs text-[#626751]">{pillar.owner}</p><p className="mt-4 border-t border-[#ded3c6] pt-4 text-xs text-[#626751]">Giai đoạn: <b>{pillar.stage}</b></p>{pillar.status === "available" && <button onClick={() => setAdoptOpen(true)} className="mt-4 w-full rounded-full bg-[#ba466d] py-2.5 text-xs font-semibold text-white">Đăng ký nhận nuôi</button>}</article>)}</div></div></section>
      <section className="bg-[#6e8644] px-5 py-24 text-[#fffaf3] lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e8cda8]">Hành trình sau thu hoạch</p><h2 className="mt-4 max-w-2xl font-serif text-5xl leading-tight">Từ Vườn Đến Bàn Ăn<br /><em className="font-normal text-[#e8cda8]">Nhanh Chóng</em></h2><p className="mt-5 max-w-xl leading-7 text-white/75">Sau khi đạt độ chín chuẩn, thanh long được thu hoạch, sơ chế và chuẩn bị giao đến người nhận nuôi trong thời gian tối ưu.</p><div className="mt-12 grid gap-5 md:grid-cols-3">{["Thu Hoạch Sạch", "Đóng Gói Tiêu Chuẩn", "Giao Tận Nhà 48H"].map((title, i) => <article key={title} className="overflow-hidden rounded-3xl bg-white/10"><div className="relative h-52"><Image src={stages[(i + 1) % stages.length].image} alt="" fill className="object-cover" />{/* TODO: Replace with real post-harvest image */}</div><div className="p-6"><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-white/70">{["Thanh long được thu hoạch thủ công đúng độ chín tại vùng trồng.", "Sản phẩm được phân loại, vệ sinh và đóng gói theo quy trình an toàn thực phẩm.", "Đơn hàng được chuẩn bị nhanh chóng để giữ tối đa độ tươi."][i]}</p></div></article>)}</div><div className="mt-8 rounded-2xl border border-white/20 bg-white/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3 text-sm"><span>Đơn thu hoạch của bạn</span><span className="text-[#e8cda8]">Thu hoạch → Sơ chế → Đóng gói → Giao hàng</span></div><div className="mt-4 h-1 rounded-full bg-white/20"><div className="h-1 w-3/4 rounded-full bg-[#e8cda8]" /></div></div></div></section>
      <section id="dang-ky" className="bg-[#fffaf3] px-5 py-28 text-center lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">Bắt đầu ngay hôm nay</p><h2 className="mx-auto mt-5 max-w-3xl font-serif text-5xl leading-tight text-[#822944]">Bắt Đầu Hành Trình<br /><em className="font-normal text-[#6e8644]">Nông Nghiệp Số Cùng Long Gia</em></h2><p className="mx-auto mt-5 max-w-lg leading-7 text-[#626751]">Nhận nuôi một trụ thanh long và đồng hành cùng người nông dân qua từng giai đoạn phát triển của cây.</p><button onClick={() => setAdoptOpen(true)} className="mt-8 rounded-full bg-[#ba466d] px-7 py-3.5 font-semibold text-white">Đăng Ký Nhận Nuôi</button></section>
    </main>
    <Footer />
    <Dialog open={adoptOpen} onOpenChange={setAdoptOpen}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl border-[#ded3c6] bg-[#fffaf3] sm:max-w-lg"><DialogHeader><DialogTitle className="font-serif text-3xl text-[#822944]">{success ? "Đăng ký thành công" : "Đăng Ký Nhận Nuôi Thanh Long"}</DialogTitle><DialogDescription>{success ? "Cảm ơn bạn. Đây là trạng thái mô phỏng cho prototype Long Gia Nhà Tôi." : "Vui lòng điền thông tin để nhận thông tin trụ thanh long và lựa chọn gói phù hợp."}</DialogDescription></DialogHeader>{success ? <div className="rounded-2xl bg-[#e4e8ce] p-6 text-center text-[#6e8644]"><Check className="mx-auto" /><p className="mt-3 font-semibold">Thông tin đã được ghi nhận</p></div> : <div className="flex flex-col gap-4"><label className="text-sm font-semibold">Họ và tên<input className="mt-2 w-full rounded-xl border border-[#d7cabb] bg-white px-4 py-3" placeholder="Nhập họ và tên..." /></label><label className="text-sm font-semibold">Số điện thoại / Zalo<input className="mt-2 w-full rounded-xl border border-[#d7cabb] bg-white px-4 py-3" placeholder="Nhập số điện thoại..." /></label><label className="text-sm font-semibold">Loại thanh long<select className="mt-2 w-full rounded-xl border border-[#d7cabb] bg-white px-4 py-3"><option>Thanh Long Ruột Đỏ HTP</option><option>Thanh Long Ruột Trắng</option><option>Thanh Long Vỏ Vàng</option></select></label><label className="text-sm font-semibold">Số trụ muốn nhận nuôi<div className="mt-2 grid grid-cols-5 gap-2">{[1, 2, 3, 5, 10].map(n => <button type="button" key={n} className="rounded-xl border border-[#d7cabb] py-3 text-sm hover:border-[#ba466d]">{n}</button>)}</div></label><label className="text-sm font-semibold">Thời gian nhận nuôi<select className="mt-2 w-full rounded-xl border border-[#d7cabb] bg-white px-4 py-3"><option>3 tháng</option><option>6 tháng</option><option>12 tháng</option></select></label></div>}<DialogFooter>{!success && <Button onClick={() => setSuccess(true)} className="rounded-full bg-[#ba466d] hover:bg-[#822944]">Xác nhận & Thanh toán</Button>}</DialogFooter></DialogContent></Dialog>
  </div>
}

function PlaceholderIcon() { return <MapPin /> }
