"use client"

import { useState } from "react"
import { ArrowUpRight, Box, Leaf, MapPin, Ship, Weight } from "lucide-react"
import { Footer } from "@/components/footer"
import { SiteHeader } from "@/components/site-header"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

const categories = ["Tất cả sản phẩm", "Thanh long ruột đỏ", "Thanh long ruột trắng", "Thanh long vỏ vàng", "Dừa", "Bưởi"]
const products = [
  { name: "Thanh Long Ruột Đỏ", category: "Thanh long ruột đỏ", descriptor: "Vị ngọt đậm đà, sắc tím hồng rực rỡ.", image: "/images/product-red-htp-transparent.png", accent: "#ba466d", note: "Tiền Giang · Xuất khẩu" },
  { name: "Thanh Long Ruột Trắng", category: "Thanh long ruột trắng", descriptor: "Thanh mát, giòn nhẹ, tinh khiết.", image: "/images/thanh-long-ruot-trang.png", accent: "#6e8644", note: "Chợ Gạo · Cung ứng quanh năm" },
  { name: "Thanh Long Vỏ Vàng", category: "Thanh long vỏ vàng", descriptor: "Dòng cao cấp với vị ngọt tinh tế.", image: "/images/thanh-long-vo-vang.png", accent: "#b58a3d", note: "Tiền Giang · Premium" },
  { name: "Dừa Kim Cương", category: "Dừa", descriptor: "Tạo hình sang trọng, nước ngọt thanh.", image: "/images/dua-kim-cuong-transparent.png", accent: "#6e8644", note: "Tiền Giang · Fresh coconut" },
  { name: "Dừa Nắp Bật", category: "Dừa", descriptor: "Mở nắp tiện lợi, giữ trọn vị tự nhiên.", image: "/images/dua-nhan-nut-transparent.png", accent: "#ba466d", note: "Tiền Giang · Ready to drink" },
  { name: "Bưởi Da Xanh", category: "Bưởi", descriptor: "Mọng nước, vị ngọt thanh, hậu chua dịu.", image: "/images/buoi-da-xanh-transparent.png", accent: "#6e8644", note: "Tiền Giang · Fresh pomelo" },
]

const details = [
  { type: "THANH LONG / 01", name: "Thanh Long Ruột Đỏ", copy: "Được trồng trên vùng đất Tiền Giang màu mỡ, thanh long ruột đỏ thu hút nhờ sắc tím hồng rực rỡ và vị ngọt đậm đà vượt trội. Sản phẩm mang đến hương vị nhiệt đới phong phú, ấn tượng và đầy cuốn hút.", season: "Tháng 5 – Tháng 9 (Cung ứng quanh năm)", feature: "Ruột tím hồng đậm, độ ngọt cao, kết cấu mềm mọng nước.", image: products[0].image },
  { type: "THANH LONG / 02", name: "Thanh Long Ruột Trắng", copy: "Được tuyển chọn từ những vườn cây ăn trái trứ danh tại Tiền Giang, thanh long ruột trắng mang đến sự kết hợp hoàn hảo giữa vị ngọt thanh và độ giòn đặc trưng. Với lớp vỏ hồng rực rỡ cùng phần ruột trắng trong trẻo, sản phẩm được ưa chuộng trên toàn thế giới như một món ăn nhẹ lành mạnh.", season: "Tháng 5 – Tháng 9 (Cung ứng quanh năm)", feature: "Vị ngọt thanh mát, thịt quả chắc giòn, lớp tai xanh tươi bắt mắt.", image: products[1].image },
  { type: "THANH LONG / 03", name: "Thanh Long Vỏ Vàng", copy: "Dòng sản phẩm cao cấp gây ấn tượng bởi lớp vỏ vàng ươm rực rỡ và vị ngọt thanh mát, tinh tế. Sở hữu chỉ số Brix cao cùng hương thơm thoang thoảng đặc trưng.", season: "Cung cấp quanh năm (Rộ vụ từ tháng 6 – tháng 10)", feature: "Vỏ vàng ươm, ruột trắng trong, thịt quả giòn nhẹ và mọng nước.", image: products[2].image },
  { type: "DỪA / 04", name: "Dừa Kim Cương", copy: "Tuyển chọn từ thủ phủ dừa Tiền Giang, dừa gọt kim cương sở hữu hình dáng góc cạnh sang trọng, giúp tối ưu diện tích lưu trữ và vận chuyển. Sản phẩm giữ trọn lượng nước dừa ngọt thanh tự nhiên.", season: "Cung ứng quanh năm.", feature: "Tạo hình đẹp mắt, gọn gàng, dễ bảo quản, nước dừa ngọt thanh.", image: products[3].image },
  { type: "DỪA / 05", name: "Dừa Nắp Bật", copy: "Giải pháp giải khát hoàn hảo cho nhịp sống bận rộn nhờ công nghệ nắp bật thông minh. Chỉ với một thao tác nhấn đơn giản, người tiêu dùng có thể thưởng thức ngay dòng nước dừa tươi mát.", season: "Cung ứng quanh năm.", feature: "Nút nhấn tiện lợi, mở nắp an toàn, giữ nguyên vị ngọt nguyên bản.", image: products[4].image },
  { type: "TRÁI CÂY / 06", name: "Bưởi Da Xanh", copy: "Bưởi da xanh được tuyển chọn từ vùng trồng Tiền Giang, nổi bật với múi mọng nước, vị ngọt thanh và hậu chua dịu. Sản phẩm phù hợp cho thị trường tiêu dùng tươi và các đơn hàng nông sản nhiệt đới chất lượng cao.", season: "Cung ứng theo mùa.", feature: "Giàu vitamin C và chất xơ, múi mọng nước, dễ thưởng thức.", image: products[5].image },
]

export function ProductPage() {
  const [category, setCategory] = useState(categories[0])
  const [quoteProduct, setQuoteProduct] = useState("")
  const [open, setOpen] = useState(false)
  const visible = category === categories[0] ? products : products.filter((item) => item.category === category)
  const quote = (name = "") => { setQuoteProduct(name); setOpen(true) }

  return <div className="min-h-screen bg-[#f0e8dd] text-[#2d3026]">
    <SiteHeader />

    <main className="pt-28">
      <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8 lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#ba466d]">Sản phẩm Long Gia</p><h1 className="mt-6 max-w-2xl font-serif text-6xl leading-[.9] tracking-[-.05em] text-[#822944] sm:text-7xl">Từ Việt Nam<br /><em className="font-normal text-[#6e8644]">vươn xa ra thế giới</em></h1><p className="mt-7 max-w-xl leading-7 text-[#626751]">Mỗi sản phẩm của HTX Hưng Thịnh Phát là một kiệt tác của nông nghiệp Việt Nam, được chăm chút tỉ mỉ và bảo chứng chất lượng bởi GlobalGAP, HACCP cùng chứng nhận OCOP 4 sao.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#bo-suu-tap" className="rounded-full bg-[#ba466d] px-6 py-3.5 text-sm font-bold text-white transition hover:-translate-y-1 hover:bg-[#822944]">Khám phá sản phẩm <ArrowUpRight className="ml-2 inline" /></a><button onClick={() => quote()} className="rounded-full border border-[#ba466d]/40 px-6 py-3.5 text-sm font-bold text-[#822944]">Yêu cầu báo giá</button></div></div><div className="relative min-h-[480px] overflow-hidden rounded-[38px] bg-[#b0bc78] shadow-2xl"><img src="/images/product-origin-tien-giang.png" alt="Hộp trái cây Long Gia từ vùng đất Tiền Giang" className="absolute inset-0 size-full object-cover transition duration-700 hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#2e3825]/70 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 text-white"><p className="font-serif text-3xl">Từ vùng đất Tiền Giang</p><p className="mt-1 text-sm text-white/75">Chuẩn sạch · Sẵn sàng xuất khẩu</p></div></div></section>

      <section id="bo-suu-tap" className="bg-[#fffaf3] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ba466d]">Danh mục</p><h2 className="mt-4 font-serif text-5xl text-[#822944]">Danh Mục Sản Phẩm Chính</h2><div className="mt-8 flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full border px-4 py-2.5 text-sm transition ${category === item ? "border-[#822944] bg-[#822944] text-white" : "border-[#d9cbbd] text-[#626751] hover:border-[#ba466d] hover:text-[#822944]"}`}>{item}</button>)}</div><div className="mt-16 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map((item, index) => <article key={item.name} className={`group overflow-hidden rounded-[28px] border border-[#e0d5c9] bg-[#f0e8dd]/45 transition hover:-translate-y-2 hover:shadow-xl ${index === 0 ? "lg:col-span-2" : ""}`}><div className={`${index === 0 ? "h-[360px]" : "h-72"} overflow-hidden`}><img src={item.image} alt={item.name} className="size-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em]" style={{ color: item.accent }}>{item.note}</p><h3 className="mt-3 font-serif text-2xl text-[#822944]">{item.name}</h3></div><span className="rounded-full bg-white px-2 py-1 text-xs text-[#ba466d]">0{products.indexOf(item) + 1}</span></div><p className="mt-3 text-sm leading-6 text-[#626751]">{item.descriptor}</p><div className="mt-5 flex flex-wrap gap-4 text-sm font-bold"><a href={`#product-${products.indexOf(item)}`} className="text-[#ba466d]">Xem chi tiết <ArrowUpRight className="ml-1 inline" /></a><button onClick={() => quote(item.name)} className="text-[#822944]">Yêu cầu báo giá</button></div></div></article>)}</div></div></section>

      <section className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ba466d]">Quy cách cung ứng</p><h2 className="mt-4 font-serif text-5xl text-[#822944]">Sẵn sàng cho từng thị trường</h2><div className="mt-12 grid gap-5 lg:grid-cols-2">{[{title: "Thanh long", products: "Ruột đỏ · Ruột trắng · Vỏ vàng", origin: "Huyện Chợ Gạo, Tiền Giang", weight: "450–600g", pack: "4KG / 10KG thùng carton", delivery: "Đường biển · Đường hàng không"}, {title: "Dừa", products: "Dừa kim cương · Dừa nắp bật", origin: "Tỉnh Tiền Giang", weight: "1.1kg – 1.5kg", pack: "9 quả / 12 quả thùng carton", delivery: "Đường biển · Đường hàng không"}].map((item) => <div key={item.title} className="rounded-[28px] border border-[#d9cbbd] bg-[#fffaf3] p-7 lg:p-9"><div className="flex items-center justify-between"><h3 className="font-serif text-3xl text-[#822944]">{item.title}</h3><Leaf className="text-[#6e8644]" /></div><p className="mt-3 text-sm text-[#626751]">{item.products}</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{[[MapPin, "Xuất xứ", item.origin], [Weight, "Trọng lượng", item.weight], [Box, "Đóng gói", item.pack], [Ship, "Giao hàng", item.delivery]].map(([Icon, label, text]) => <div key={label as string} className="flex gap-3"><span className="mt-1 text-[#ba466d]"><Icon /></span><div><p className="text-xs font-bold uppercase tracking-widest text-[#626751]">{label as string}</p><p className="mt-1 text-sm leading-5 text-[#2d3026]">{text as string}</p></div></div>)}</div></div>)}</div></div></section>

      <section className="bg-[#fffaf3] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ba466d]">Khám phá sản phẩm</p><h2 className="mt-4 max-w-2xl font-serif text-5xl leading-tight text-[#822944]">Tươi ngon từ vùng trồng<br /><em className="font-normal text-[#6e8644]">đến từng lô hàng</em></h2><div className="mt-16 flex flex-col gap-24">{details.map((item, index) => <article id={`product-${index}`} key={item.name} className="grid gap-10 lg:grid-cols-2 lg:items-center"><div className={`overflow-hidden rounded-[34px] ${index % 2 ? "lg:order-2" : ""}`}><img src={item.image} alt={item.name} className="aspect-[4/5] w-full object-cover transition duration-700 hover:scale-[1.02]" />{/* TODO: Replace with real product image */}</div><div className={index % 2 ? "lg:order-1" : ""}><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ba466d]">{item.type}</p><h3 className="mt-5 font-serif text-4xl text-[#822944]">{item.name}</h3><p className="mt-6 leading-7 text-[#626751]">{item.copy}</p><div className="mt-7 grid gap-4 border-y border-[#d9cbbd] py-5 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-[#6e8644]">Mùa vụ chính</p><p className="mt-2 text-sm text-[#626751]">{item.season}</p></div><div><p className="text-xs font-bold uppercase tracking-widest text-[#6e8644]">Đặc điểm nổi bật</p><p className="mt-2 text-sm text-[#626751]">{item.feature}</p></div></div><button onClick={() => quote(item.name)} className="mt-7 rounded-full bg-[#ba466d] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#822944]">Yêu cầu báo giá <ArrowUpRight className="ml-1 inline" /></button></div></article>)}</div></div></section>

      <section id="bao-gia" className="bg-[#6e8644] px-5 py-24 text-[#fffaf3] lg:px-8 lg:py-28"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#e8cda8]">Hợp tác & phân phối</p><h2 className="mt-5 font-serif text-5xl leading-tight sm:text-6xl">Bạn đang tìm nguồn cung<br /><em className="font-normal text-[#e8cda8]">nông sản chất lượng?</em></h2><p className="mx-auto mt-6 max-w-xl leading-7 text-white/75">Chúng tôi sẵn sàng hỗ trợ nhu cầu mua sỉ, phân phối, gia công đóng gói và xuất khẩu theo yêu cầu của từng đối tác.</p><button onClick={() => quote()} className="mt-8 rounded-full bg-[#fffaf3] px-7 py-3.5 text-sm font-bold text-[#822944] transition hover:bg-[#e8cda8]">YÊU CẦU BÁO GIÁ</button><p className="mt-5 text-sm text-white/70">Để được hỗ trợ nhanh nhất, vui lòng gọi tới (+84) 0919 831 055</p></div></section>
    </main><Footer />

    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto border-[#d9cbbd] bg-[#fffaf3] sm:max-w-2xl"><DialogHeader><DialogTitle className="font-serif text-3xl text-[#822944]">Yêu Cầu Báo Giá</DialogTitle><DialogDescription className="text-[#626751]">Rất vui khi nhận được yêu cầu hợp tác từ Quý khách! Vui lòng điền thông tin bên dưới.</DialogDescription></DialogHeader>{quoteProduct && <div className="rounded-xl bg-[#f0e8dd] px-4 py-3 text-sm text-[#822944]">Sản phẩm quan tâm: <strong>{quoteProduct}</strong></div>}<form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); setOpen(false) }}><div className="grid gap-4 sm:grid-cols-2"><Input required placeholder="Họ và tên" /><Input required type="email" placeholder="Email" /><Input placeholder="Số điện thoại / Zalo" /><Input placeholder="Đơn vị / Địa chỉ" /></div><Input placeholder="Tiêu đề" /><Textarea placeholder="Nội dung chi tiết hoặc yêu cầu báo giá của bạn..." rows={5} /><Input placeholder="Mã bảo vệ" /><div className="flex flex-wrap justify-end gap-3"><Button type="reset" variant="outline" className="border-[#d9cbbd] text-[#822944]">NHẬP LẠI</Button><Button type="submit" className="bg-[#ba466d] hover:bg-[#822944]">GỬI THÔNG TIN</Button></div></form></DialogContent></Dialog>
  </div>
}

export default ProductPage
